name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: springbootreactjs
  DOCKER_TAG: 0.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 자바 및 메이븐 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. 메이븐으로 빌드
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      # 4. Docker Hub 로그인 (독립된 스텝)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 태그 생성 (독립된 스텝)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/springbootreactjs
          tags: |
            type=raw,value=0.2
            type=raw,value=latest

      # 6. Docker 빌드 및 푸시 (독립된 스텝)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}