name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: springbootreactjs
  DOCKER_TAG: 0.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          # [수정 1] $DOCKER_IMAGE -> ${{ env.DOCKER_IMAGE }} 로 변경
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}

          # [수정 2] $DOCKER_TAG -> ${{ env.DOCKER_TAG }} 로 변경
          tags: ${{ env.DOCKER_TAG }}

          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}